version: "3.7"
services:
  crypto-oracle:
    image: registry.digitalocean.com/biggestfan/crypto/crypto-oracle:${TAG_CRYPTO_ORACLE:-latest}
    build:
      context: ${CRYPTO_ORACLE_DIR:-./}
      dockerfile: ./Dockerfile
    volumes:
      - ./data/:/app/data/
    networks: 
      - bitcoin-bridging
    command: gunicorn --bind 0.0.0.0:2222 --timeout=600 exchange:app -w 1 --threads 5

networks:
  bitcoin-bridging:
    external: true
    