name: Functional test

on: [push]

jobs:
  test-on-newman:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Creare bitcoin-bridging network
        run: docker network create bitcoin-bridging
      - name: Run crypto-oracle container
        run: cd exchange-oracle && docker-compose up
      - name: install newman
        run: npm install
      - name: Run newman
        run: npx newman run integration-tests/oracle/Get_Exchange_rate.postman_collection.json -g integration-tests/oracle/Oracle.postman_globals.json


