
name: Functional test
on: [push]
jobs:
  Setup Newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install newman
      - run: npm install

jobs:
  Run test on Newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run test
      - run: npx 